// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ShippingWeight")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specifications")
                        .HasMaxLength(650)
                        .HasColumnType("nvarchar(650)");

                    b.Property<string>("Tags")
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cat-1",
                            Dimensions = "23x45",
                            ImageURL = "https://image.com/img2132",
                            Model = "MXC-3952",
                            Name = "Product1",
                            Price = 100.45f,
                            ShippingWeight = "50",
                            Specifications = "Spec-1",
                            Tags = "Product | Cat-1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cat-2",
                            Dimensions = "34x24",
                            ImageURL = "https://image.com/img2133",
                            Model = "MXC-3953",
                            Name = "Product2",
                            Price = 23.53f,
                            ShippingWeight = "30",
                            Specifications = "Spec-2",
                            Tags = "Product | Cat-2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cat-3",
                            Dimensions = "22x32",
                            ImageURL = "https://image.com/img2134",
                            Model = "MXC-3954",
                            Name = "Product3",
                            Price = 373.35f,
                            ShippingWeight = "35",
                            Specifications = "Spec-3",
                            Tags = "Product | Cat-3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cat-4",
                            Dimensions = "23x46",
                            ImageURL = "https://image.com/img2135",
                            Model = "MXC-3955",
                            Name = "Product4",
                            Price = 438.67667f,
                            ShippingWeight = "23.33",
                            Specifications = "Spec-4",
                            Tags = "Product | Cat-4"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cat-5",
                            Dimensions = "34x25",
                            ImageURL = "https://image.com/img2136",
                            Model = "MXC-3956",
                            Name = "Product5",
                            Price = 575.12665f,
                            ShippingWeight = "15.83",
                            Specifications = "Spec-5",
                            Tags = "Product | Cat-5"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Cat-6",
                            Dimensions = "22x33",
                            ImageURL = "https://image.com/img2137",
                            Model = "MXC-3957",
                            Name = "Product6",
                            Price = 711.57666f,
                            ShippingWeight = "8.33",
                            Specifications = "Spec-6",
                            Tags = "Product | Cat-6"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cat-7",
                            Dimensions = "23x47",
                            ImageURL = "https://image.com/img2138",
                            Model = "MXC-3958",
                            Name = "Product7",
                            Price = 848.0267f,
                            ShippingWeight = "0.83",
                            Specifications = "Spec-7",
                            Tags = "Product | Cat-7"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Cat-8",
                            Dimensions = "34x26",
                            ImageURL = "https://image.com/img2139",
                            Model = "MXC-3959",
                            Name = "Product8",
                            Price = 984.4767f,
                            ShippingWeight = "6.66",
                            Specifications = "Spec-8",
                            Tags = "Product | Cat-8"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Cat-9",
                            Dimensions = "22x34",
                            ImageURL = "https://image.com/img2140",
                            Model = "MXC-3960",
                            Name = "Product9",
                            Price = 1120.9266f,
                            ShippingWeight = "14.16",
                            Specifications = "Spec-9",
                            Tags = "Product | Cat-9"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Cat-10",
                            Dimensions = "23x48",
                            ImageURL = "https://image.com/img2141",
                            Model = "MXC-3961",
                            Name = "Product10",
                            Price = 1257.3767f,
                            ShippingWeight = "21.66",
                            Specifications = "Spec-10",
                            Tags = "Product | Cat-10"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Cat-11",
                            Dimensions = "34x27",
                            ImageURL = "https://image.com/img2142",
                            Model = "MXC-3962",
                            Name = "Product11",
                            Price = 1393.8267f,
                            ShippingWeight = "29.16",
                            Specifications = "Spec-11",
                            Tags = "Product | Cat-11"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Cat-12",
                            Dimensions = "22x35",
                            ImageURL = "https://image.com/img2143",
                            Model = "MXC-3963",
                            Name = "Product12",
                            Price = 1530.2766f,
                            ShippingWeight = "36.66",
                            Specifications = "Spec-12",
                            Tags = "Product | Cat-12"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Cat-13",
                            Dimensions = "23x49",
                            ImageURL = "https://image.com/img2144",
                            Model = "MXC-3964",
                            Name = "Product13",
                            Price = 1666.7267f,
                            ShippingWeight = "44.16",
                            Specifications = "Spec-13",
                            Tags = "Product | Cat-13"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Cat-14",
                            Dimensions = "34x28",
                            ImageURL = "https://image.com/img2145",
                            Model = "MXC-3965",
                            Name = "Product14",
                            Price = 1803.1766f,
                            ShippingWeight = "51.66",
                            Specifications = "Spec-14",
                            Tags = "Product | Cat-14"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Cat-15",
                            Dimensions = "22x36",
                            ImageURL = "https://image.com/img2146",
                            Model = "MXC-3966",
                            Name = "Product15",
                            Price = 1939.6267f,
                            ShippingWeight = "59.16",
                            Specifications = "Spec-15",
                            Tags = "Product | Cat-15"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Cat-16",
                            Dimensions = "23x50",
                            ImageURL = "https://image.com/img2147",
                            Model = "MXC-3967",
                            Name = "Product16",
                            Price = 2076.0767f,
                            ShippingWeight = "66.66",
                            Specifications = "Spec-16",
                            Tags = "Product | Cat-16"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Cat-17",
                            Dimensions = "34x29",
                            ImageURL = "https://image.com/img2148",
                            Model = "MXC-3968",
                            Name = "Product17",
                            Price = 2212.5266f,
                            ShippingWeight = "74.16",
                            Specifications = "Spec-17",
                            Tags = "Product | Cat-17"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Cat-18",
                            Dimensions = "22x36",
                            ImageURL = "https://image.com/img2149",
                            Model = "MXC-3969",
                            Name = "Product18",
                            Price = 2348.9766f,
                            ShippingWeight = "81.66",
                            Specifications = "Spec-18",
                            Tags = "Product | Cat-18"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Cat-19",
                            Dimensions = "23x50",
                            ImageURL = "https://image.com/img2150",
                            Model = "MXC-3970",
                            Name = "Product19",
                            Price = 2485.4268f,
                            ShippingWeight = "89.16",
                            Specifications = "Spec-19",
                            Tags = "Product | Cat-19"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cat-20",
                            Dimensions = "34x29",
                            ImageURL = "https://image.com/img2151",
                            Model = "MXC-3971",
                            Name = "Product20",
                            Price = 2621.8767f,
                            ShippingWeight = "96.66",
                            Specifications = "Spec-20",
                            Tags = "Product | Cat-20"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Cat-21",
                            Dimensions = "22x37",
                            ImageURL = "https://image.com/img2152",
                            Model = "MXC-3972",
                            Name = "Product21",
                            Price = 2758.3267f,
                            ShippingWeight = "104.16",
                            Specifications = "Spec-21",
                            Tags = "Product | Cat-21"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Cat-22",
                            Dimensions = "23x51",
                            ImageURL = "https://image.com/img2153",
                            Model = "MXC-3973",
                            Name = "Product22",
                            Price = 2894.7766f,
                            ShippingWeight = "111.66",
                            Specifications = "Spec-22",
                            Tags = "Product | Cat-22"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Cat-23",
                            Dimensions = "34x30",
                            ImageURL = "https://image.com/img2154",
                            Model = "MXC-3974",
                            Name = "Product23",
                            Price = 3031.2266f,
                            ShippingWeight = "119.16",
                            Specifications = "Spec-23",
                            Tags = "Product | Cat-23"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Cat-24",
                            Dimensions = "22x37",
                            ImageURL = "https://image.com/img2155",
                            Model = "MXC-3975",
                            Name = "Product24",
                            Price = 3167.6768f,
                            ShippingWeight = "126.66",
                            Specifications = "Spec-24",
                            Tags = "Product | Cat-24"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Cat-25",
                            Dimensions = "23x51",
                            ImageURL = "https://image.com/img2156",
                            Model = "MXC-3976",
                            Name = "Product25",
                            Price = 3304.1267f,
                            ShippingWeight = "134.16",
                            Specifications = "Spec-25",
                            Tags = "Product | Cat-25"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Cat-26",
                            Dimensions = "34x30",
                            ImageURL = "https://image.com/img2157",
                            Model = "MXC-3977",
                            Name = "Product26",
                            Price = 3440.5767f,
                            ShippingWeight = "141.66",
                            Specifications = "Spec-26",
                            Tags = "Product | Cat-26"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Cat-27",
                            Dimensions = "22x38",
                            ImageURL = "https://image.com/img2158",
                            Model = "MXC-3978",
                            Name = "Product27",
                            Price = 3577.0266f,
                            ShippingWeight = "149.16",
                            Specifications = "Spec-27",
                            Tags = "Product | Cat-27"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Cat-28",
                            Dimensions = "23x52",
                            ImageURL = "https://image.com/img2159",
                            Model = "MXC-3979",
                            Name = "Product28",
                            Price = 3713.4766f,
                            ShippingWeight = "156.66",
                            Specifications = "Spec-28",
                            Tags = "Product | Cat-28"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Cat-29",
                            Dimensions = "34x31",
                            ImageURL = "https://image.com/img2160",
                            Model = "MXC-3980",
                            Name = "Product29",
                            Price = 3849.9268f,
                            ShippingWeight = "164.16",
                            Specifications = "Spec-29",
                            Tags = "Product | Cat-29"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Cat-30",
                            Dimensions = "22x38",
                            ImageURL = "https://image.com/img2161",
                            Model = "MXC-3981",
                            Name = "Product30",
                            Price = 3986.3767f,
                            ShippingWeight = "171.66",
                            Specifications = "Spec-30",
                            Tags = "Product | Cat-30"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Cat-31",
                            Dimensions = "23x52",
                            ImageURL = "https://image.com/img2162",
                            Model = "MXC-3982",
                            Name = "Product31",
                            Price = 4122.8267f,
                            ShippingWeight = "179.16",
                            Specifications = "Spec-31",
                            Tags = "Product | Cat-31"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Cat-32",
                            Dimensions = "34x31",
                            ImageURL = "https://image.com/img2163",
                            Model = "MXC-3983",
                            Name = "Product32",
                            Price = 4259.277f,
                            ShippingWeight = "186.66",
                            Specifications = "Spec-32",
                            Tags = "Product | Cat-32"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Cat-33",
                            Dimensions = "22x39",
                            ImageURL = "https://image.com/img2164",
                            Model = "MXC-3984",
                            Name = "Product33",
                            Price = 4395.7266f,
                            ShippingWeight = "194.16",
                            Specifications = "Spec-33",
                            Tags = "Product | Cat-33"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Cat-34",
                            Dimensions = "23x53",
                            ImageURL = "https://image.com/img2165",
                            Model = "MXC-3985",
                            Name = "Product34",
                            Price = 4532.177f,
                            ShippingWeight = "201.66",
                            Specifications = "Spec-34",
                            Tags = "Product | Cat-34"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Cat-35",
                            Dimensions = "34x32",
                            ImageURL = "https://image.com/img2166",
                            Model = "MXC-3986",
                            Name = "Product35",
                            Price = 4668.6265f,
                            ShippingWeight = "209.16",
                            Specifications = "Spec-35",
                            Tags = "Product | Cat-35"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Cat-36",
                            Dimensions = "22x39",
                            ImageURL = "https://image.com/img2167",
                            Model = "MXC-3987",
                            Name = "Product36",
                            Price = 4805.0767f,
                            ShippingWeight = "216.66",
                            Specifications = "Spec-36",
                            Tags = "Product | Cat-36"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Cat-37",
                            Dimensions = "23x53",
                            ImageURL = "https://image.com/img2168",
                            Model = "MXC-3988",
                            Name = "Product37",
                            Price = 4941.527f,
                            ShippingWeight = "224.16",
                            Specifications = "Spec-37",
                            Tags = "Product | Cat-37"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Cat-38",
                            Dimensions = "34x32",
                            ImageURL = "https://image.com/img2169",
                            Model = "MXC-3989",
                            Name = "Product38",
                            Price = 5077.9766f,
                            ShippingWeight = "231.66",
                            Specifications = "Spec-38",
                            Tags = "Product | Cat-38"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Cat-39",
                            Dimensions = "22x40",
                            ImageURL = "https://image.com/img2170",
                            Model = "MXC-3990",
                            Name = "Product39",
                            Price = 5214.427f,
                            ShippingWeight = "239.16",
                            Specifications = "Spec-39",
                            Tags = "Product | Cat-39"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Cat-40",
                            Dimensions = "23x54",
                            ImageURL = "https://image.com/img2171",
                            Model = "MXC-3991",
                            Name = "Product40",
                            Price = 5350.8765f,
                            ShippingWeight = "246.66",
                            Specifications = "Spec-40",
                            Tags = "Product | Cat-40"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Cat-41",
                            Dimensions = "34x33",
                            ImageURL = "https://image.com/img2172",
                            Model = "MXC-3992",
                            Name = "Product41",
                            Price = 5487.3267f,
                            ShippingWeight = "254.16",
                            Specifications = "Spec-41",
                            Tags = "Product | Cat-41"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Cat-42",
                            Dimensions = "22x40",
                            ImageURL = "https://image.com/img2173",
                            Model = "MXC-3993",
                            Name = "Product42",
                            Price = 5623.777f,
                            ShippingWeight = "261.66",
                            Specifications = "Spec-42",
                            Tags = "Product | Cat-42"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Cat-43",
                            Dimensions = "23x54",
                            ImageURL = "https://image.com/img2174",
                            Model = "MXC-3994",
                            Name = "Product43",
                            Price = 5760.2266f,
                            ShippingWeight = "269.16",
                            Specifications = "Spec-43",
                            Tags = "Product | Cat-43"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Cat-44",
                            Dimensions = "34x33",
                            ImageURL = "https://image.com/img2175",
                            Model = "MXC-3995",
                            Name = "Product44",
                            Price = 5896.677f,
                            ShippingWeight = "276.66",
                            Specifications = "Spec-44",
                            Tags = "Product | Cat-44"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Cat-45",
                            Dimensions = "22x41",
                            ImageURL = "https://image.com/img2176",
                            Model = "MXC-3996",
                            Name = "Product45",
                            Price = 6033.1265f,
                            ShippingWeight = "284.16",
                            Specifications = "Spec-45",
                            Tags = "Product | Cat-45"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Cat-46",
                            Dimensions = "23x55",
                            ImageURL = "https://image.com/img2177",
                            Model = "MXC-3997",
                            Name = "Product46",
                            Price = 6169.5767f,
                            ShippingWeight = "291.66",
                            Specifications = "Spec-46",
                            Tags = "Product | Cat-46"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Cat-47",
                            Dimensions = "34x34",
                            ImageURL = "https://image.com/img2178",
                            Model = "MXC-3998",
                            Name = "Product47",
                            Price = 6306.027f,
                            ShippingWeight = "299.16",
                            Specifications = "Spec-47",
                            Tags = "Product | Cat-47"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Cat-48",
                            Dimensions = "22x41",
                            ImageURL = "https://image.com/img2179",
                            Model = "MXC-3999",
                            Name = "Product48",
                            Price = 6442.4766f,
                            ShippingWeight = "306.66",
                            Specifications = "Spec-48",
                            Tags = "Product | Cat-48"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Cat-49",
                            Dimensions = "23x55",
                            ImageURL = "https://image.com/img2180",
                            Model = "MXC-4000",
                            Name = "Product49",
                            Price = 6578.927f,
                            ShippingWeight = "314.16",
                            Specifications = "Spec-49",
                            Tags = "Product | Cat-49"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Cat-50",
                            Dimensions = "34x34",
                            ImageURL = "https://image.com/img2181",
                            Model = "MXC-4001",
                            Name = "Product50",
                            Price = 6715.3765f,
                            ShippingWeight = "321.66",
                            Specifications = "Spec-50",
                            Tags = "Product | Cat-50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
